import React from 'react';
import { render } from '@testing-library/react';

/**
 * Default mock values for the useMarketplace context.
 * Individual tests can override any key via the `contextOverrides` option.
 */
export const defaultContextValues = {
  apiBaseUrl: 'https://example.com/wp-json/marketplace/v1/plugins/',
  useWPHandlers: true,
  wpConfig: {
    ajaxUrl: 'https://example.com/wp-admin/admin-ajax.php',
    nonce: 'test-nonce-123',
    adminUrl: 'https://example.com/wp-admin/',
    rankMathRegistrationSkip: false,
  },
  enableDefaultStyles: false,
  assetsBaseUrl: 'https://example.com/assets/',
  pluginInAction: {},
  setPluginInAction: jest.fn(),
  subscriptionsList: [],
  setSubscriptionsList: jest.fn(),
  subscriptionStatus: {},
  isCheckingSubscription: {},
  fetchPartnerSubscriptions: jest.fn(),
  fetchSubscriptionStatus: jest.fn(),
  isOnecomBrand: true,
  plugins: [],
  setPlugins: jest.fn(),
  uiI18n: {},
  setUiI18n: jest.fn(),
  handlePluginAction: jest.fn(),
  handleCancelSubsAction: jest.fn(),
  cancelReload: jest.fn(),
  loadingAction: '',
  setLoadingAction: jest.fn(),
  loadingPlugin: '',
  setLoadingPlugin: jest.fn(),
  noticeState: { visible: false, type: null, pluginSlug: null },
  setNoticeState: jest.fn(),
  errorState: { visible: false, type: null, pluginSlug: null },
  setErrorState: jest.fn(),
  successState: { visible: false, type: null, pluginSlug: null },
  setSuccessState: jest.fn(),
  allPluginsActivated: false,
  setAllPluginsActivated: jest.fn(),
  catalogError: false,
  setCatalogError: jest.fn(),
  catalogLoading: false,
  setCatalogLoading: jest.fn(),
  currentPluginSlug: null,
  setCurrentPluginSlug: jest.fn(),
  deleteModalState: { isOpen: false, plugin: null },
  openDeleteModal: jest.fn(),
  closeDeleteModal: jest.fn(),
  shouldShowProvision: jest.fn().mockReturnValue( false ),
  isSpecialPlugin: jest.fn().mockReturnValue( false ),
  shouldShowPlugin: jest.fn().mockReturnValue( true ),
  isWpVersionSupported: jest.fn().mockReturnValue( true ),
  wpVersion: '6.7',
  activePlugins: [],
  activeThemeAuthor: '',
  pendingProcurements: {},
  setPendingProcurements: jest.fn(),
};
